// Auto-generated by @emitio/codegen
// Source: /Users/movibe/sites/libs/logger/packages/codegen/test-schema.yaml

export interface AnalyticsEvents {
  'page_viewed': {
  page_name: string
  referrer?: string
}
  'button_clicked': {
  button_id: string
  label: string
}
  'user_signed_up': {
  method: string
}
  'purchase': {
  order_id: string
  total: number
  currency: string
  items?: number
}
}
