// Auto-generated by @movibe/logger-codegen
// Source: /Users/movibe/sites/libs/logger/packages/codegen/test-schema.yaml

import type { LoggerStrategy } from '@movibe/logger'
import type { AnalyticsEvents } from '/Users/movibe/sites/libs/logger/packages/codegen/test-schema.types.ts'


export function createTracker(client: LoggerStrategy<AnalyticsEvents>) {
  return {
  /** Fired when a user views a page */
  pageViewed(params: AnalyticsEvents['page_viewed']) {
    client.event('page_viewed', params)
  }

  /** Fired when a user clicks a button */
  buttonClicked(params: AnalyticsEvents['button_clicked']) {
    client.event('button_clicked', params)
  }

  /** Fired when a new user completes registration */
  userSignedUp(params: AnalyticsEvents['user_signed_up']) {
    client.event('user_signed_up', params)
  }

  purchase(params: AnalyticsEvents['purchase']) {
    client.event('purchase', params)
  }
  }
}
