import { relative } from 'node:path'
import type { ParsedEvent, ParsedField } from './types.js'

function toCamelCase(snake: string): string {
  return snake.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
}

function fieldToTs(field: ParsedField): string {
  const opt = field.optional ? '?' : ''
  const desc = field.description ? `  /** ${field.description} */\n` : ''
  return `${desc}    ${field.name}${opt}: ${field.type}`
}

function fieldsToTs(fields: ParsedField[]): string {
  if (fields.length === 0) return 'Record<string, never>'
  return `{\n${fields.map(f => fieldToTs(f)).join('\n')}\n  }`
}

export interface GeneratedOutput {
  types: string
  tracker: string
}

export function generate(
  events: ParsedEvent[],
  schemaPath: string,
  outDir: string,
  typesFile: string
): GeneratedOutput {
  const typesImportPath = './' + typesFile.replace(/\.ts$/, '.js')

  const eventTypeEntries = events.map(e =>
    `  '${e.name}': ${fieldsToTs(e.fields)}`
  ).join('\n')

  const types = `// Auto-generated by @emit-io/codegen
// Source: ${schemaPath}

export interface AnalyticsEvents {
${eventTypeEntries}
}
`

  const trackerMethods = events.map(e => {
    const methodName = toCamelCase(e.name)
    const desc = e.description ? `/** ${e.description} */\n  ` : ''
    const hasFields = e.fields.length > 0
    const paramType = hasFields ? `params: AnalyticsEvents['${e.name}']` : 'params?: Record<string, never>'
    const callArgs = hasFields ? `'${e.name}', params` : `'${e.name}'`

    return `  ${desc}${methodName}(${paramType}) {
    client.event(${callArgs})
  }`
  }).join('\n\n')

  const tracker = `// Auto-generated by @emit-io/codegen
// Source: ${schemaPath}

import type { LoggerStrategy } from '@emit-io/core'
import type { AnalyticsEvents } from '${typesImportPath}'


export function createTracker(client: LoggerStrategy<AnalyticsEvents>) {
  return {
${trackerMethods}
  }
}
`

  return { types, tracker }
}
